training:
  n_epochs: 5000
  batch_size: 8
  num_workers: 4
  eval_freq: 50
  scale_factor: 1.141876
  use_ema: true
  ema_decay: 0.999
  use_precomputed_latents: true
  roi_size: [64, 64, 64] #only used if latents are not precomputed

optim:
  lr: 1e-4
  lr_gamma: 0.9995

model:
  params:
    spatial_dims: 3
    in_channels: 8
    out_channels: 8
    num_res_blocks: 2
    num_channels: [64, 128, 256, 512]
    attention_levels: [false, false, true, true]
    with_conditioning: false
    num_head_channels: [0, 0, 32, 32]
    use_flash_attention: true

scheduler:
  schedule: "cosine"
  num_train_timesteps: 1000
  prediction_type: "v_prediction"
