training:
  n_epochs: 4000
  batch_size: 2
  num_workers: 4
  eval_freq: 100
  scale_factor: 1.11
  use_ema: true
  ema_decay: 0.999
  use_precomputed_latents: true  # set to false if you want to train on raw images
  roi_size: [64, 64, 64] #only used if latents are not precomputed

optim:
  lr: 5e-5
  lr_gamma: 0.9995

model:
  params:
    spatial_dims: 3
    in_channels: 8
    out_channels: 8
    num_res_blocks: 3
    num_channels: [128, 256, 512]
    attention_levels: [false, false, true]
    with_conditioning: false
    num_head_channels: [0, 0, 64]
    use_flash_attention: true

scheduler:
  schedule: "cosine"
  num_train_timesteps: 300
  prediction_type: "v_prediction"
